### ISSUE TITLE
XCM MultiLocation Written Format

### ISSUE THREAD

**Issue by ryanleecode** [paraspell/xcm-tools#188]
Given a scale or JSON encoded XCM MultiLocation, there should be a tool that converts it into its [human readable written format](https://github.com/paritytech/xcm-format?tab=readme-ov-file#written-format).

**Comment by dudo50** [comment]
Hey @ryanleecode, thank you for your suggestion! We will look into this shortly and let you kniw if we have any questions for you regarding this feature/tool you requested. 

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
@ryanleecode , we had deep dive to this issue. Could you please confirm us, if we understand correctly?

So you wish us to create function/tool/package, that converts lenghty JSON to something like this? : 
``` ../Parachain(2OO6)/Account(randomAddr)/PalletInstance(50)/GeneralIndex(1984)/Amount(randomAmount)```

The above would be translated from :
```
//Parachain multilocation
V3:
    parents: '1'
    interior:
      X1:
        Parachain: 2,006

//Address multilocation
  V3:
    parents: '0'
    interior:
      X1:
        AccountId32:
          network: null
          id: 'accountID'

//Currency and amount multilocation
  V3:
    - id:
        Concrete:
          parents: '0'
          interior:
            X2:
              - PalletInstance: '50'
              - GeneralIndex: 1,984
      fun:
        Fungible: amount

```

If we understand your request correctly, could you please specify if the output format we mentioned suits your needs and if not, how would you format the output of the tool? Thanks you!
